### ISSUE TITLE
Feature: Make the project more contributor friendly

### ISSUE THREAD

**Issue by orama254** [lucalves/draven-theme#12]
Greetings @lucalves 

as per Github's recommended community standards, the project seems to be missing some items on the checklist namely

- [x] Code of conduct #13 
- [x] Contributing guidelines #14 

#### screenshot:
![draven-theme](https://user-images.githubusercontent.com/50571688/135822748-ee65cbc6-d4b4-4f85-8a00-83c7e500b949.jpg)

I'd be happy to add them to the project if you need any assistance with this

**Comment by lucalves** [comment]
It would be very interesting if you could work on these patterns, thank you! @orama254

**Comment by orama254** [comment]
> It would be very interesting if you could work on these patterns, thank you! @orama254

cool, working on them

**Comment by lucalves** [comment]
> Greetings @lucalves
> 
> as per Github's recommended community standards, the project seems to be missing some items on the checklist namely
> 
> * [x]  Code of conduct [docs: Add code of conduct to the project #13](https://github.com/lucalves/draven-theme/pull/13)
> * [x]  Contributing guidelines [docs: Add contributing guidelines to the project #14](https://github.com/lucalves/draven-theme/pull/14)
> 
> #### screenshot:
> ![draven-theme](https://user-images.githubusercontent.com/50571688/135822748-ee65cbc6-d4b4-4f85-8a00-83c7e500b949.jpg)
> 
> I'd be happy to add them to the project if you need any assistance with this

Out of curiosity, what tool did you use to perform these metrics?

**Comment by orama254** [comment]
> > Greetings @lucalves
> > as per Github's recommended community standards, the project seems to be missing some items on the checklist namely
> > 
> > * [x]   Code of conduct [docs: Add code of conduct to the project #13](https://github.com/lucalves/draven-theme/pull/13)
> > * [x]   Contributing guidelines [docs: Add contributing guidelines to the project #14](https://github.com/lucalves/draven-theme/pull/14)
> > 
> > #### screenshot:
> > ![draven-theme](https://user-images.githubusercontent.com/50571688/135822748-ee65cbc6-d4b4-4f85-8a00-83c7e500b949.jpg)
> > I'd be happy to add them to the project if you need any assistance with this
> 
> Out of curiosity, what tool did you use to perform these metrics?

You can go to the insights tab on your github repo then after that click on the community tab again. You will get all the info about the recomended community standards

#### step 1
![step-1](https://user-images.githubusercontent.com/50571688/136093270-eb942924-a90e-4696-9ac3-17ca98256e63.jpg)

#### step 2
![step-2](https://user-images.githubusercontent.com/50571688/136093354-2920cba4-3dcb-4c42-8618-0234ce5ed92b.jpg)
