### ISSUE TITLE
Template for create issues

### ISSUE THREAD

**Issue by lucalves** [lucalves/draven-theme#17]
We need a standard Issues format, in order to standardize the project and facilitate screening.

We can use the following topics:

### The Issue is...

- [ ] Feature Request 
- [ ] Bug Report
- [ ] Other

### Description
A clear and concise description of what the issue is about.

### How to reproduce
If this issue is describing a bug, include some steps to reproduce the behavior.

**Comment by nebocoder** [comment]
Hello, I can add the issue template 😊

**Comment by lucalves** [comment]
> Hello, I can add the issue template 😊

Thanks, you can go ahead! I will sign for you.
