### ISSUE TITLE
Include a template for creating Issues in the project

### ISSUE THREAD

**Issue by lucalves** [lucalves/draven-theme#8]
# Why?

A standard Issues format is interesting, in order to standardize the project and facilitate screening.

**Comment by nayan2306** [comment]
Can you berif it once?

**Comment by nayan2306** [comment]
I would like to work for this

**Comment by lucalves** [comment]
> Can you berif it once?

Yeah! We can include three templates for Issues:

![issues](https://user-images.githubusercontent.com/17712401/135727375-13818963-3edd-4288-b2c3-c6e6423e23e6.png)

And we can include the following topics for each of them:

1. Is your feature/bug request related to a problem? Please describe.

2. Describe the solution you'd like

3. Additional context

And for help request topic, we can use a blank Issue.

**Comment by nayan2306** [comment]
So what I do?
